### ISSUE TITLE
Fatal error in MPI_Init_thread: Other MPI error, error stack:

### ISSUE THREAD

**Issue by madsheiervang** [conda-forge/fenics-feedstock#44] opened 2017-06-14 08:37 UTC
I've installed FEniCS through Anaconda on Mac OS X 10.12. When trying to run the first tutorial script I encounter the following error. 

(fenicsproject) $ python ft01_poisson.py 
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, cylon.local (errno 1)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=3191311
:
system msg for write_line failure : Bad file descriptor

Problem was solved by Johannes Ring:

"I have tested this on macOS 10.12 with both Python 2 and Python 3, and 
they both works fine for me. I used this command to install: 

conda create -n fenicsproject-py36 -c conda-forge fenics python=3.6 
source activate fenicsproject-py36 

Does this give you the same problem? If so, then please report the 
issue at https://github.com/conda-forge/fenics-feedstock/issues. "

**Comment by bmmi** [comment] 2017-09-21 03:04
I tried both python 2.7 and 3.6 on Mac OS X 10.12, same error!

**Comment by minrk** [comment] 2017-09-21 07:09
@bmmi what's `conda list`?

**Comment by bmmi** [comment] 2017-09-21 13:23
blas                      1.1                    openblas    conda-forge
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cmake                     3.9.1                         0    conda-forge
curl                      7.54.1                        0    conda-forge
eigen                     3.3.3                         0    conda-forge
expat                     2.2.1                         0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
fenics                    2017.1.0            np113py36_6    conda-forge
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
hdf5                      1.8.18                        0    conda-forge
icu                       58.1                          1    conda-forge
krb5                      1.14.2                        0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libssh2                   1.8.0                         1    conda-forge
libuv                     1.11.0                        0    conda-forge
metis                     5.1.0                         3    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpich                     3.2                           4    conda-forge
mpmath                    0.19                     py36_2    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.13.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0    conda-forge
pcre                      8.39                          0    conda-forge
petsc                     3.7.6           blas_openblas_0  [blas_openblas]  conda-forge
petsc4py                  3.7.0                    py36_1    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pkg-config                0.29.1                        1    conda-forge
ply                       3.10                     py36_0    conda-forge
ptscotch                  6.0.4                         2    conda-forge
python                    3.6.2                         0    conda-forge
readline                  6.2                           0    conda-forge
rhash                     1.3.4                         0    conda-forge
setuptools                36.3.0                   py36_0    conda-forge
six                       1.11.0                     py_0    conda-forge
slepc                     3.7.4                         0    conda-forge
slepc4py                  3.7.0                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
swig                      3.0.12                        2    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tbb                       2018_20170726                 0    conda-forge
tk                        8.5.19                        2    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

**Comment by WolferStyle** [comment] 2017-09-23 19:07
I am having the exact same problem as bmmi. I also have the same results from conda list.

**Comment by kalefranz** [comment] 2017-10-17 21:35
I was also able to reproduce this.

```
$ /conda/envs/fenicsproject/bin/python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 23:08:53)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dolfin
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(474)..............:
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................:
MPID_nem_init(320).................:
MPID_nem_tcp_init(173).............:
MPID_nem_tcp_get_business_card(420):
MPID_nem_tcp_init(379).............: gethostbyname failed, 0283 (errno 1)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=3191311
:
system msg for write_line failure : Bad file descriptor
```

```
$ /conda/bin/conda list -p /conda/envs/fenicsproject
# packages in environment at /conda/envs/fenicsproject:
#
blas                      1.1                    openblas    conda-forge
boost                     1.63.0                   py27_5    conda-forge
boost-cpp                 1.63.0                        2    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py27_0    conda-forge
cmake                     3.9.3                         0    conda-forge
curl                      7.54.1                        0    conda-forge
eigen                     3.3.3                         0    conda-forge
expat                     2.2.1                         0    conda-forge
fastcache                 1.0.2                    py27_0    conda-forge
fenics                    2016.2.0                 py27_6    conda-forge
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py27_1    conda-forge
hdf5                      1.8.18                        1    conda-forge
icu                       58.1                          1    conda-forge
krb5                      1.14.2                        0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libssh2                   1.8.0                         1    conda-forge
libuv                     1.11.0                        0    conda-forge
metis                     5.1.0                         3    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpich                     3.2                           5    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.13.3          py27_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0    conda-forge
pcre                      8.39                          0    conda-forge
petsc                     3.7.6           blas_openblas_0  [blas_openblas]  conda-forge
petsc4py                  3.7.0                    py27_1    conda-forge
pip                       9.0.1                    py27_0    conda-forge
pkg-config                0.29.1                        1    conda-forge
ply                       3.10                     py27_0    conda-forge
ptscotch                  6.0.4                         4    conda-forge
python                    2.7.14                        0    conda-forge
readline                  6.2                           0    conda-forge
rhash                     1.3.4                         0    conda-forge
scotch                    6.0.4                         3    conda-forge
setuptools                36.6.0                   py27_1    conda-forge
six                       1.11.0                   py27_1    conda-forge
slepc                     3.7.4                         0    conda-forge
slepc4py                  3.7.0                    py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
subprocess32              3.2.7                    py27_0    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
swig                      3.0.11                        0    conda-forge
sympy                     1.1.1                    py27_0    conda-forge
tbb                       2018_20170919                 0    conda-forge
tk                        8.5.19                        2    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

```
$ /conda/bin/conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.30.post1+b178e1f21
       conda is private : False
      conda-env version : 4.3.30.post1+b178e1f21
    conda-build version : 2.1.17+11.g5ebf736b
         python version : 2.7.12.final.0
       requests version : 2.12.0
       root environment : /conda  (writable)
    default environment : /conda
       envs directories : /conda/envs
                          /Users/kfranz/.conda/envs
          package cache : /conda/pkgs
                          /Users/kfranz/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/kfranz/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30.post1+b178e1f21 requests/2.12.0 CPython/2.7.12 Darwin/17.0.0 OSX/10.13
                UID:GID : 502:20
```

```
$ uname -a
Darwin 0283 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

**Comment by georgreen** [comment] 2017-10-20 10:05
<img width="831" alt="screen shot 2017-10-20 at 12 51 50 1" src="https://user-images.githubusercontent.com/17669596/31815559-ba0f1f10-b595-11e7-8b1f-e23e016c7d7f.png">

- I encountered a similar situation, as shown above(while using mpich), I found a solution to this though, as the traceback from the error says ` getHostByName failed`: to resolve this just add your hostname to your `etc/host` file.
## OR
- Set a host name by `sudo scutil --set HostName <my_new_host_name>`:  replace <my_new_host_name> with a custom name

- Then add it to your `etc/host` file by `sudo vim /etc/hosts`

- I assume you are running a UNIX like OS.
- I found this here `https://stackoverflow.com/questions/23112515/mpich2-gethostbyname-failed`

**Comment by oalii** [comment] 2017-10-27 12:20
Hi, 
I am also dealing with the same issue since today. The thing is, fenics worked just fine yesterday (was able to run some tutorials) ... and I did not change anything on my computer in the meantime (at least not on purpose). Does that make any sense ?

**Comment by minrk** [comment] 2017-10-30 08:31
@oalii from the above errors and the successful fix, it sounds like it's a local DNS issue.

In Python, does the following work when you are seeing the error with mpi:

```python
import socket
print(socket.gethostname())
print(socket.gethostbyname(socket.gethostname()))
```

**Comment by oalii** [comment] 2017-10-30 08:59
Hi @minrk,
Thx for the insight.
I tried @georgreen procedure and it worked, indeed.
I am not really familiar with these DNS-related issues, do you have some ref I could check to learn a bit more ?
Thx again !

**Comment by prakharrr** [comment] 2020-02-26 19:59
Any status on this? I seem to be getting the same issue. 
I've reinstalled every piece of package from the scratch even unlinked brew kegs and linked them again to remove any missing symlinks but no help :(

**Comment by jan-janssen** [comment] 2021-11-18 14:32
This should be fixed now, otherwise feel free to open a new issue.

**Closed by jan-janssen** 2021-11-18 14:32 UTC
