### ISSUE TITLE
Installation of FEniCS via conda fails, because of missing shared libraries for MUMPS-MPI

### ISSUE THREAD

**Issue by hoelzlw** [conda-forge/fenics-feedstock#90] opened 2019-07-04 14:56 UTC
Issue:
When installing FEniCS via conda, it pulls the package **mumps-mpi**, version **5.1.2**, build **blas_openblash08140c7_1001**  [blas_openblas].
This package of mumps, however, does not contain shared libraries, but only static ones.

Trying to import dolfin consequently results in the following error
ImportError: libdmumps-5.1.2.so: cannot open shared object file: No such file or directory

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
binutils_impl_linux-64    2.31.1               h6176602_1  
binutils_linux-64         2.31.1               h6176602_7  
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cmake                     3.14.5               hf94ab9c_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
eigen                     3.3.7             h6bb024c_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fenics                    2019.1.0                 py37_3    conda-forge
fenics-dijitso            2019.1.0                   py_3    conda-forge
fenics-dolfin             2019.1.0         py37h80b64ce_3    conda-forge
fenics-ffc                2019.1.0                   py_3    conda-forge
fenics-fiat               2019.1.0                   py_3    conda-forge
fenics-libdolfin          2019.1.0             h9041177_3    conda-forge
fenics-ufl                2019.1.0                   py_3    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
hdf5                      1.10.4          mpi_mpich_ha7d0aea_1006    conda-forge
hypre                     2.15.1            hc98498a_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0           5_h6e990d7_netlib    conda-forge
libcblas                  3.8.0           5_h6e990d7_netlib    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0           5_h6e990d7_netlib    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuv                     1.30.1               h516909a_0    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                ha14ba45_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             hc99cbb1_1012    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mumps-mpi                 5.1.2           blas_openblash08140c7_1001  [blas_openblas]  conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
parmetis                  4.0.3             hb1a587f_1002    conda-forge
petsc                     3.11.1               h624fa55_1    conda-forge
petsc4py                  3.11.0           py37h906564f_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkgconfig                 1.3.1                 py37_1001    conda-forge
ptscotch                  6.0.6             h5a4526e_1002    conda-forge
pybind11                  2.2.4           py37hc9558a2_1001    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
scalapack                 2.0.2             h2831592_1005    conda-forge
scotch                    6.0.6             h491eb26_1002    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
slepc                     3.11.1               h00d104f_0    conda-forge
slepc4py                  3.11.0           py37hce3d510_0    conda-forge
sqlite                    3.28.0               hcee41ef_1    conda-forge
suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.7               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
System 1: CentOS 7.5.1804

```
$ conda info
     active environment : fenics
    active env location : /home/hoelzlw/miniconda3/envs/fenics
            shell level : 2
       user config file : /home/hoelzlw/.condarc
 populated config files : /home/hoelzlw/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /home/hoelzlw/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/hoelzlw/miniconda3/pkgs
                          /home/hoelzlw/.conda/pkgs
       envs directories : /home/hoelzlw/miniconda3/envs
                          /home/hoelzlw/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Linux/3.10.0-862.3.3.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1302:200
             netrc file : None
           offline mode : False
```
System 2: Windows 10 1809, WSL Ubuntu 18.04

```
$ conda info
     active environment : FEniCS
    active env location : /home/hoelzlw/miniconda3/envs/FEniCS
            shell level : 3
       user config file : /home/hoelzlw/.condarc
 populated config files : /home/hoelzlw/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /home/hoelzlw/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/hoelzlw/miniconda3/pkgs
                          /home/hoelzlw/.conda/pkgs
       envs directories : /home/hoelzlw/miniconda3/envs
                          /home/hoelzlw/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-17763-Microsoft ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

<br/>
Steps to reproduce:
<details>
Install miniconda:

```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh -b
./miniconda3/bin/conda update -n base conda
```
Create environment for FEniCS:
```
./miniconda3/bin/conda create --name fenics
./miniconda3/bin/conda activate fenics
```
Install FEniCS
```
conda install -c conda-forge fenics
```
Try to import dolfin
```
python -c "from dolfin import *"
```
Error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hoelzlw/miniconda3/envs/fenics/lib/python3.7/site-packages/dolfin/__init__.py", line 34, in <module>
    from .cpp import __version__
ImportError: libdmumps-5.1.2.so: cannot open shared object file: No such file or directory
```
</details>

There are other conda packages of MUMPS-MPI which contain shared libraries, but none of these can be installed into the FEniCS-environment because _the specifications are found to be incompatible with each other_.

Best regards
Wolfgang

**Comment by francescoboc** [comment] 2019-07-11 09:58
+1 Have exactly the same problem

**Comment by hoelzlw** [comment] 2019-07-22 12:21
Apparently, this does not happen with conda 4.6.14, but with 4.7.10.
So, not calling `./miniconda3/bin/conda update -n base conda` in the steps above results in working fenics environment.

I don't know, which version of conda introduced this.

Additionally, now with 4.7.10 dolfin seems to work, even though, libdmumps-5.1.2.so is still missing.
At least, I don't get the ImportError anymore.
However, I cannot ensure, that still everything is okay under the hood.


The difference in installed packages between conda-4.6.14 and conda-4.7.10 is the following:

```
$ diff <(conda list -n fenics-conda-4.6.14) <(conda list -n fenics-conda-4.7.10)
1c1
< # packages in environment at /home/hoelzlw/miniconda3-4.6.14/envs/fenics-conda-4.6.14:
---
> # packages in environment at /home/hoelzlw/miniconda3-4.6.14/envs/fenics-conda-4.7.10:
6a7
> blas                      1.1                    openblas    conda-forge
33,34c34,35
< libblas                   3.8.0               10_openblas    conda-forge
< libcblas                  3.8.0               10_openblas    conda-forge
---
> libblas                   3.8.0           5_h6e990d7_netlib    conda-forge
> libcblas                  3.8.0           5_h6e990d7_netlib    conda-forge
40,41c41
< liblapack                 3.8.0               10_openblas    conda-forge
< libopenblas               0.3.6                h6e990d7_4    conda-forge
---
> liblapack                 3.8.0           5_h6e990d7_netlib    conda-forge
52,53c52
< mumps-include             5.1.2                      1007    conda-forge
< mumps-mpi                 5.1.2             h5bebb2f_1007    conda-forge
---
> mumps-mpi                 5.1.2           blas_openblash08140c7_1001  [blas_openblas]  conda-forge
55,56c54,55
< numpy                     1.15.4          py37h8b7e671_1002    conda-forge
< openblas                  0.3.6                h6e990d7_4    conda-forge
---
> numpy                     1.15.4          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
> openblas                  0.3.3             h9ac9557_1001    conda-forge
76c75
< suitesparse               4.5.6             heab0a99_1202    conda-forge
---
> suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
```

It seems, that something under the libaries' hood changed, resulting in incompatible packages.

As a solution, I recommend the FEniCS developers to use version pinning in the conda recipe.
I mean, instead of alwalys pulling the latest version of PETSc, MUMPS, etc., pull some version, where FEniCS is guaranteed to work.

I cannot really do this, as I have no idea, which versions of the external dependencies result in a FEniCS installation which works for sure.

**Comment by hoelzlw** [comment] 2019-07-22 12:45
Now it is also not reproducible anymore when using conda-4.7.5 by updating 4.6.14 via `conda install conda==4.7.5`.
Even though, libdmumps-5.1.2.so is still missing, dolfin seems to work., so I close this issue now.

I still heavily recommend to introduce version pinning in the conda recipe to prevent such strange issues in the future.

Best regards
Wolfgang

**Comment by francescoboc** [comment] 2019-07-25 13:01
I just tried to install FEniCS using conda 4.7.10 and if i try to import dolfin I still get `ImportError: libdmumps-5.1.2.so: cannot open shared object file: No such file or directory`.
@hoelzlw , what did you do exactly to make it work?

**Comment by hoelzlw** [comment] 2019-07-25 15:26
I tested with the wrong system. -.-
Apparently, my test system had mumps installed correctly, so I couldn't reproduce it anymore.
Now I switched to a fresh CentOS 7.5.1804 and can reproduce it again, so I reopen this issue.
</br>

At first:
**FEniCS seems to work with conda-4.6.14.**

Environment at 4.6.14 (<code>/tmp/hoelzlw/miniconda3-4.6.14/bin/conda list --name fenics-conda-4.6.14</code>):
<details>

```
# packages in environment at /tmp/hoelzlw/miniconda3-4.6.14/envs/fenics-conda-4.6.14:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cmake                     3.14.5               hf94ab9c_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
eigen                     3.3.7             h6bb024c_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fenics                    2019.1.0                 py37_3    conda-forge
fenics-dijitso            2019.1.0                   py_3    conda-forge
fenics-dolfin             2019.1.0         py37h80b64ce_3    conda-forge
fenics-ffc                2019.1.0                   py_3    conda-forge
fenics-fiat               2019.1.0                   py_3    conda-forge
fenics-libdolfin          2019.1.0             h9041177_3    conda-forge
fenics-ufl                2019.1.0                   py_3    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
hdf5                      1.10.4          mpi_mpich_ha7d0aea_1006    conda-forge
hypre                     2.15.1            hc98498a_1001    conda-forge
icu                       64.2                 he1b5a44_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
liblapack                 3.8.0               10_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_5    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libuv                     1.30.1               h516909a_0    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                ha14ba45_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             hc99cbb1_1013    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mumps-include             5.1.2                      1007    conda-forge
mumps-mpi                 5.1.2             h5bebb2f_1007    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4          py37h8b7e671_1002    conda-forge
openblas                  0.3.6                h6e990d7_5    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
parmetis                  4.0.3             hb1a587f_1002    conda-forge
petsc                     3.11.1               h624fa55_1    conda-forge
petsc4py                  3.11.0           py37h906564f_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkgconfig                 1.3.1                 py37_1001    conda-forge
ptscotch                  6.0.6             h5a4526e_1002    conda-forge
pybind11                  2.2.4           py37hc9558a2_1001    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
scalapack                 2.0.2             h2831592_1005    conda-forge
scotch                    6.0.6             h491eb26_1002    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
slepc                     3.11.1               h00d104f_0    conda-forge
slepc4py                  3.11.0           py37hce3d510_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
suitesparse               4.5.6             heab0a99_1202    conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.7               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```
</details>

At second:
**FEniCS does not work anymore with conda-4.7.5**, because at least libdmumps-5.1.2.so is missing.
I don't know, whether further libraries are missing, because I cannot proceed beyond this error.

Environment at 4.7.5 (<code>/tmp/hoelzlw/miniconda3-4.7.5/bin/conda list --name fenics-conda-4.7.5</code>):
<details>

```
# packages in environment at /tmp/hoelzlw/miniconda3-4.7.5/envs/fenics-conda-4.7.5:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cmake                     3.14.5               hf94ab9c_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
eigen                     3.3.7             h6bb024c_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fenics                    2019.1.0                 py37_3    conda-forge
fenics-dijitso            2019.1.0                   py_3    conda-forge
fenics-dolfin             2019.1.0         py37h80b64ce_3    conda-forge
fenics-ffc                2019.1.0                   py_3    conda-forge
fenics-fiat               2019.1.0                   py_3    conda-forge
fenics-libdolfin          2019.1.0             h9041177_3    conda-forge
fenics-ufl                2019.1.0                   py_3    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
hdf5                      1.10.4          mpi_mpich_ha7d0aea_1006    conda-forge
hypre                     2.15.1            hc98498a_1001    conda-forge
icu                       64.2                 he1b5a44_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0           6_h6e990d7_netlib    conda-forge
libcblas                  3.8.0           6_h6e990d7_netlib    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
liblapack                 3.8.0           6_h6e990d7_netlib    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libuv                     1.30.1               h516909a_0    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                ha14ba45_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             hc99cbb1_1013    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mumps-mpi                 5.1.2           blas_openblash08140c7_1001  [blas_openblas]  conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
parmetis                  4.0.3             hb1a587f_1002    conda-forge
petsc                     3.11.1               h624fa55_1    conda-forge
petsc4py                  3.11.0           py37h906564f_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkgconfig                 1.3.1                 py37_1001    conda-forge
ptscotch                  6.0.6             h5a4526e_1002    conda-forge
pybind11                  2.2.4           py37hc9558a2_1001    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
scalapack                 2.0.2             h2831592_1005    conda-forge
scotch                    6.0.6             h491eb26_1002    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
slepc                     3.11.1               h00d104f_0    conda-forge
slepc4py                  3.11.0           py37hce3d510_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.7               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```
</details>

Difference between these two (<code>diff <(/tmp/hoelzlw/miniconda3-4.6.14/bin/conda list --name fenics-conda-4.6.14) <(/tmp/hoelzlw/miniconda3-4.7.5/bin/conda list --name fenics-conda-4.7.5)</code>):
<details>

```
1c1
< # packages in environment at /tmp/hoelzlw/miniconda3-4.6.14/envs/fenics-conda-4.6.14:
---
> # packages in environment at /tmp/hoelzlw/miniconda3-4.7.5/envs/fenics-conda-4.7.5:
6a7
> blas                      1.1                    openblas    conda-forge
33,34c34,35
< libblas                   3.8.0               10_openblas    conda-forge
< libcblas                  3.8.0               10_openblas    conda-forge
---
> libblas                   3.8.0           6_h6e990d7_netlib    conda-forge
> libcblas                  3.8.0           6_h6e990d7_netlib    conda-forge
40,41c41
< liblapack                 3.8.0               10_openblas    conda-forge
< libopenblas               0.3.6                h6e990d7_5    conda-forge
---
> liblapack                 3.8.0           6_h6e990d7_netlib    conda-forge
52,53c52
< mumps-include             5.1.2                      1007    conda-forge
< mumps-mpi                 5.1.2             h5bebb2f_1007    conda-forge
---
> mumps-mpi                 5.1.2           blas_openblash08140c7_1001  [blas_openblas]  conda-forge
55,56c54,55
< numpy                     1.15.4          py37h8b7e671_1002    conda-forge
< openblas                  0.3.6                h6e990d7_5    conda-forge
---
> numpy                     1.15.4          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
> openblas                  0.3.3             h9ac9557_1001    conda-forge
76c75
< suitesparse               4.5.6             heab0a99_1202    conda-forge
---
> suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
```
</details>
</br>

There is no version of conda between 4.6.14 and 4.7.5.
The latest version of conda right now is 4.7.10 and leads to the same list of packages as 4.7.5.

So we are back again with a non-working FEniCS via conda because of missing shared libraries.

However, one can *fix* this by not upgrading conda beyond version 4.6.14.

**Comment by shuds13** [comment] 2019-08-01 23:43
I have this issue with a different code. Explicitly using conda install mumps-mpi=5.1.2=h5bebb2f_1007 works for me.

**Comment by clason** [comment] 2019-08-02 08:10
@shuds13 For me it was `conda install -c conda-forge mumps-mpi=5.1.2=haf446c3_1007`, but yes, this works!

**Comment by astern** [comment] 2019-08-02 10:03
> On Aug 2, 2019, at 9:11 AM, Christian Clason <notifications@github.com> wrote:
> 
> @shuds13 For me it was conda install -c conda-forge mumps-mpi=5.1.2=haf446c3_1007, but yes, this works!

I can confirm that "conda install -c conda-forge mumps-mpi=5.1.2=haf446c3_1007" solved the problem for me, too. Thanks!

Cheers,
Ari

**Comment by minrk** [comment] 2019-08-02 18:00
I believe this is fixed by the latest builds of petsc and fenics 2019.1 (which pull in mumps-mpi 5.2.1)

**Closed by minrk** 2019-08-02 18:00 UTC
