### ISSUE TITLE
libfortran.so.4 error on import fenics

### ISSUE THREAD

**Issue by ondrejtichacek** [conda-forge/fenics-feedstock#68] opened 2018-09-11 15:55 UTC
Issue:

I have problem with installing fenics with Anaconda, Ubuntu 16.04. I follow the instructions I found at https://fenicsproject.org/download/, however, when I try to run my python script, I get the following error:

```
Traceback (most recent call last):
  File "diffusion_K.py", line 1, in <module>
    from fenics import *
  File "/home/ondrej/anaconda3/envs/fenicsproject/lib/python3.6/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/home/ondrej/anaconda3/envs/fenicsproject/lib/python3.6/site-packages/dolfin/__init__.py", line 34, in <module>
    from .cpp import __version__
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

After trying solution I found online (downgrade libgfortran-ng to version 7.2.0), I get another issue: `CXXABI_1.3.9 not included in libstdc++.so.6`.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/ondrej/anaconda3/envs/fenicsproject:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
boost                     1.67.0                   py36_4  
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
cloog                     0.18.0                        0  
cmake                     3.12.2               h011004d_0    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
eigen                     3.3.5                hfc679d8_1    conda-forge
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py36h470a237_1    conda-forge
fenics                    2018.1.0         py36hba71e3e_1    conda-forge
gcc                       4.8.5                         7  
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
hypre                     2.14.0               h7df9f4f_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
isl                       0.12.2                        0  
krb5                      1.14.6                        0    conda-forge
libboost                  1.67.0               h46d08c1_4  
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            8.2.0                hdf63c60_1  
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuv                     1.23.0               h7b6447c_0  
metis                     5.1.0                h470a237_3    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.0              py36_mpich_3    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
mumps-mpi                 5.1.2           blas_openblasha5050ec_0  [blas_openblas]  conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_202  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
parmetis                  4.0.3                hf0665dc_2    conda-forge
petsc                     3.9.3           blas_openblash330393b_1  [blas_openblas]  conda-forge
petsc4py                  3.9.1            py36h18b3941_1    conda-forge
pip                       18.0                     py36_1    conda-forge
pkg-config                0.29.2               h470a237_3    conda-forge
pkgconfig                 1.4.0                    py36_0  
ptscotch                  6.0.5                ha5050ec_0    conda-forge
py-boost                  1.67.0           py36h04863e7_4  
pybind11                  2.2.4            py36h2d50403_1    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
rhash                     1.3.6                hb7f436b_0  
scalapack                 2.0.2                h186ce0b_3    conda-forge
scotch                    6.0.5                h9c0d707_1    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
slepc                     3.9.2           blas_openblashe63b0ae_0  [blas_openblas]  conda-forge
slepc4py                  3.9.0            py36h7eb728f_1    conda-forge
sqlite                    3.24.0               h2f33b56_1    conda-forge
suitesparse               4.5.6           blas_openblash55dcaef_201  [blas_openblas]  conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tbb                       2018_20171205                 0    conda-forge
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : fenicsproject
    active env location : /home/ondrej/anaconda3/envs/fenicsproject
            shell level : 1
       user config file : /home/ondrej/.condarc
 populated config files : /home/ondrej/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/ondrej/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ondrej/anaconda3/pkgs
                          /home/ondrej/.conda/pkgs
       envs directories : /home/ondrej/anaconda3/envs
                          /home/ondrej/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-135-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by johannesring** [comment] 2018-09-12 07:17
You have several packages that are not from the conda-forge channel and that could cause conflicts/problems. See if it works if you install everything from conda-forge in a clean environment, like this:

``` console
conda create -n fenics-test -c conda-forge fenics
conda activate fencis-test
python -c "import dolfin"
```
Do you still have the same problem?

**Comment by ondrejtichacek** [comment] 2018-09-12 08:09
Yes, I get the same error:
```
 python -c "import dolfin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ondrej/anaconda3/envs/fenics-test/lib/python3.6/site-packages/dolfin/__init__.py", line 34, in <module>
    from .cpp import __version__
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

**Comment by johannesring** [comment] 2018-09-12 11:07
I could not reproduce this in a Ubuntu 16.04 Docker container using the following commands:

Starting the container:
``` console
docker run -ti --rm ubuntu:16.04
```
Inside the Docker container:
``` console
apt update -qqq && \
apt install -yqq wget bzip2 gcc > /dev/null && \
wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
sh Miniconda3-latest-Linux-x86_64.sh -b && \
source ~/miniconda3/etc/profile.d/conda.sh && \
conda create -yq -n fenicsproject -c conda-forge fenics && \
conda activate fenicsproject && \
conda list && \
conda info && \
python -c "import dolfin;print(dolfin.__version__)"
```
Output:
<details>

```
[johannr:~/dev/misc/newt] master(+1/-1)* 6m40s ± docker run -ti --rm ubuntu:16.04
root@35e3103876f0:/# apt update -qqq && \
> apt install -yqq wget bzip2 gcc > /dev/null && \
> wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
> sh Miniconda3-latest-Linux-x86_64.sh -b && \
> source ~/miniconda3/etc/profile.d/conda.sh && \
> conda create -yq -n fenicsproject -c conda-forge fenics && \
> conda activate fenicsproject && \
> conda list && \
> conda info && \
> python -c "import dolfin;print(dolfin.__version__)"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: delaying package configuration, since apt-utils is not installed
PREFIX=/root/miniconda3
installing: python-3.7.0-hc3d631a_0 ...
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libgcc-ng-8.2.0-hdf63c60_1 ...
installing: libstdcxx-ng-8.2.0-hdf63c60_1 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2p-h14c3975_0 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-h7b6447c_5 ...
installing: tk-8.6.8-hbc83047_0 ...
installing: sqlite-3.24.0-h84994c4_0 ...
installing: asn1crypto-0.24.0-py37_0 ...
installing: certifi-2018.8.24-py37_1 ...
installing: chardet-3.0.4-py37_1 ...
installing: idna-2.7-py37_0 ...
installing: pycosat-0.6.3-py37h14c3975_0 ...
installing: pycparser-2.18-py37_1 ...
installing: pysocks-1.6.8-py37_0 ...
installing: ruamel_yaml-0.15.46-py37h14c3975_0 ...
installing: six-1.11.0-py37_1 ...
installing: cffi-1.11.5-py37he75722e_1 ...
installing: setuptools-40.2.0-py37_0 ...
installing: cryptography-2.3.1-py37hc365091_0 ...
installing: wheel-0.31.1-py37_0 ...
installing: pip-10.0.1-py37_0 ...
installing: pyopenssl-18.0.0-py37_0 ...
installing: urllib3-1.23-py37_0 ...
installing: requests-2.19.1-py37_0 ...
installing: conda-4.5.11-py37_0 ...
installation finished.
Solving environment: ...working... done

## Package Plan ##

  environment location: /root/miniconda3/envs/fenicsproject

  added / updated specs: 
    - fenics


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-18.0                   |           py36_1         1.8 MB  conda-forge
    cmake-3.12.2               |       h011004d_0        11.6 MB  conda-forge
    readline-7.0               |       haf1bffa_1         381 KB  conda-forge
    hypre-2.14.0               |       h7df9f4f_1         1.5 MB  conda-forge
    sympy-1.1.1                |           py36_0         7.0 MB  conda-forge
    wheel-0.31.1               |           py36_1          61 KB  conda-forge
    curl-7.61.0                |       h93b3f91_2         859 KB  conda-forge
    petsc-3.9.3                |blas_openblash330393b_1         8.1 MB  conda-forge
    sqlite-3.24.0              |       h2f33b56_1         1.5 MB  conda-forge
    gmp-6.1.2                  |       hfc679d8_0         676 KB  conda-forge
    fenics-2018.1.0            |   py36hba71e3e_1        41.2 MB  conda-forge
    pybind11-2.2.4             |   py36h2d50403_1         113 KB  conda-forge
    xz-5.2.4                   |       h470a237_1         328 KB  conda-forge
    libssh2-1.8.0              |       h5b517e9_2         240 KB  conda-forge
    mpich-3.2.1                |       h26a2512_4         5.3 MB  conda-forge
    mpc-1.1.0                  |                4         127 KB  conda-forge
    slepc4py-3.9.0             |   py36h7eb728f_1         296 KB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    libffi-3.2.1               |       hfc679d8_5          51 KB  conda-forge
    openblas-0.2.20            |                8        17.0 MB  conda-forge
    isl-0.12.2                 |                0         1.1 MB
    libstdcxx-ng-7.2.0         |       hdf63c60_3         2.5 MB  conda-forge
    rhash-1.3.4                |                0         170 KB  conda-forge
    tk-8.6.8                   |                0         3.1 MB  conda-forge
    parmetis-4.0.3             |       hf0665dc_2         271 KB  conda-forge
    zlib-1.2.11                |       h470a237_3          93 KB  conda-forge
    boost-1.67.0               |   py36h3e44d54_0         316 KB  conda-forge
    libgcc-ng-7.2.0            |       hdf63c60_3         6.1 MB  conda-forge
    mumps-mpi-5.1.2            |blas_openblasha5050ec_0         2.5 MB  conda-forge
    ca-certificates-2018.8.24  |       ha4d7672_0         136 KB  conda-forge
    mpi-1.0                    |            mpich           4 KB  conda-forge
    mpmath-1.0.0               |             py_0         429 KB  conda-forge
    suitesparse-4.5.6          |blas_openblash55dcaef_201         2.1 MB  conda-forge
    openssl-1.0.2p             |       h470a237_0         3.5 MB  conda-forge
    cloog-0.18.0               |                0         617 KB
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB  conda-forge
    expat-2.2.5                |       hfc679d8_2         144 KB  conda-forge
    icu-58.2                   |       hfc679d8_0        22.8 MB  conda-forge
    scalapack-2.0.2            |       h186ce0b_3         1.4 MB  conda-forge
    python-3.6.6               |       h5001a0f_0        20.9 MB  conda-forge
    numpy-1.14.5               |py36_blas_openblashd3ea46f_202         9.0 MB  conda-forge
    ncurses-6.1                |       hfc679d8_1         1.2 MB  conda-forge
    pkg-config-0.29.2          |       h470a237_3         446 KB  conda-forge
    petsc4py-3.9.1             |   py36h18b3941_1         1.1 MB  conda-forge
    gmpy2-2.0.8                |           py36_1         629 KB  conda-forge
    gcc-4.8.5                  |                7        66.6 MB
    eigen-3.3.5                |       hfc679d8_1         962 KB  conda-forge
    mpfr-3.1.5                 |                0         406 KB  conda-forge
    certifi-2018.8.24          |           py36_1         139 KB  conda-forge
    fastcache-1.0.2            |   py36h470a237_1          48 KB  conda-forge
    slepc-3.9.2                |blas_openblashe63b0ae_0         2.5 MB  conda-forge
    scotch-6.0.5               |       h9c0d707_1         1.1 MB  conda-forge
    setuptools-40.2.0          |           py36_0         554 KB  conda-forge
    metis-5.1.0                |       h470a237_3         4.1 MB  conda-forge
    hdf5-1.10.2                |       hc401514_2         4.8 MB  conda-forge
    six-1.11.0                 |           py36_1          21 KB  conda-forge
    krb5-1.14.6                |                0         4.0 MB  conda-forge
    tbb-2018_20171205          |                0         1.2 MB  conda-forge
    boost-cpp-1.67.0           |       h3a22d5f_0        19.7 MB  conda-forge
    pkgconfig-1.3.1            |           py36_1           9 KB  conda-forge
    bzip2-1.0.6                |       h470a237_2         310 KB  conda-forge
    libuv-1.22.0               |       h470a237_1         414 KB  conda-forge
    ptscotch-6.0.5             |       ha5050ec_0         627 KB  conda-forge
    libgfortran-3.0.0          |                1         281 KB  conda-forge
    mpi4py-3.0.0               |     py36_mpich_3         2.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       290.1 MB

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                          conda-forge
    boost:           1.67.0-py36h3e44d54_0                 conda-forge
    boost-cpp:       1.67.0-h3a22d5f_0                     conda-forge
    bzip2:           1.0.6-h470a237_2                      conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0                  conda-forge
    certifi:         2018.8.24-py36_1                      conda-forge
    cloog:           0.18.0-0                                         
    cmake:           3.12.2-h011004d_0                     conda-forge
    curl:            7.61.0-h93b3f91_2                     conda-forge
    eigen:           3.3.5-hfc679d8_1                      conda-forge
    expat:           2.2.5-hfc679d8_2                      conda-forge
    fastcache:       1.0.2-py36h470a237_1                  conda-forge
    fenics:          2018.1.0-py36hba71e3e_1               conda-forge
    gcc:             4.8.5-7                                          
    gmp:             6.1.2-hfc679d8_0                      conda-forge
    gmpy2:           2.0.8-py36_1                          conda-forge
    hdf5:            1.10.2-hc401514_2                     conda-forge
    hypre:           2.14.0-h7df9f4f_1                     conda-forge
    icu:             58.2-hfc679d8_0                       conda-forge
    isl:             0.12.2-0                                         
    krb5:            1.14.6-0                              conda-forge
    libffi:          3.2.1-hfc679d8_5                      conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3                      conda-forge
    libgfortran:     3.0.0-1                               conda-forge
    libgfortran-ng:  7.2.0-hdf63c60_3                      conda-forge
    libssh2:         1.8.0-h5b517e9_2                      conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3                      conda-forge
    libuv:           1.22.0-h470a237_1                     conda-forge
    metis:           5.1.0-h470a237_3                      conda-forge
    mpc:             1.1.0-4                               conda-forge
    mpfr:            3.1.5-0                               conda-forge
    mpi:             1.0-mpich                             conda-forge
    mpi4py:          3.0.0-py36_mpich_3                    conda-forge
    mpich:           3.2.1-h26a2512_4                      conda-forge
    mpmath:          1.0.0-py_0                            conda-forge
    mumps-mpi:       5.1.2-blas_openblasha5050ec_0         conda-forge [blas_openblas]
    ncurses:         6.1-hfc679d8_1                        conda-forge
    numpy:           1.14.5-py36_blas_openblashd3ea46f_202 conda-forge [blas_openblas]
    openblas:        0.2.20-8                              conda-forge
    openssl:         1.0.2p-h470a237_0                     conda-forge
    parmetis:        4.0.3-hf0665dc_2                      conda-forge
    petsc:           3.9.3-blas_openblash330393b_1         conda-forge [blas_openblas]
    petsc4py:        3.9.1-py36h18b3941_1                  conda-forge
    pip:             18.0-py36_1                           conda-forge
    pkg-config:      0.29.2-h470a237_3                     conda-forge
    pkgconfig:       1.3.1-py36_1                          conda-forge
    ptscotch:        6.0.5-ha5050ec_0                      conda-forge
    pybind11:        2.2.4-py36h2d50403_1                  conda-forge
    python:          3.6.6-h5001a0f_0                      conda-forge
    readline:        7.0-haf1bffa_1                        conda-forge
    rhash:           1.3.4-0                               conda-forge
    scalapack:       2.0.2-h186ce0b_3                      conda-forge
    scotch:          6.0.5-h9c0d707_1                      conda-forge
    setuptools:      40.2.0-py36_0                         conda-forge
    six:             1.11.0-py36_1                         conda-forge
    slepc:           3.9.2-blas_openblashe63b0ae_0         conda-forge [blas_openblas]
    slepc4py:        3.9.0-py36h7eb728f_1                  conda-forge
    sqlite:          3.24.0-h2f33b56_1                     conda-forge
    suitesparse:     4.5.6-blas_openblash55dcaef_201       conda-forge [blas_openblas]
    sympy:           1.1.1-py36_0                          conda-forge
    tbb:             2018_20171205-0                       conda-forge
    tk:              8.6.8-0                               conda-forge
    wheel:           0.31.1-py36_1                         conda-forge
    xz:              5.2.4-h470a237_1                      conda-forge
    zlib:            1.2.11-h470a237_3                     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
# packages in environment at /root/miniconda3/envs/fenicsproject:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
cloog                     0.18.0                        0  
cmake                     3.12.2               h011004d_0    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
eigen                     3.3.5                hfc679d8_1    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fastcache                 1.0.2            py36h470a237_1    conda-forge
fenics                    2018.1.0         py36hba71e3e_1    conda-forge
gcc                       4.8.5                         7  
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
hypre                     2.14.0               h7df9f4f_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
isl                       0.12.2                        0  
krb5                      1.14.6                        0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libuv                     1.22.0               h470a237_1    conda-forge
metis                     5.1.0                h470a237_3    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.0              py36_mpich_3    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
mumps-mpi                 5.1.2           blas_openblasha5050ec_0  [blas_openblas]  conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_202  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
parmetis                  4.0.3                hf0665dc_2    conda-forge
petsc                     3.9.3           blas_openblash330393b_1  [blas_openblas]  conda-forge
petsc4py                  3.9.1            py36h18b3941_1    conda-forge
pip                       18.0                     py36_1    conda-forge
pkg-config                0.29.2               h470a237_3    conda-forge
pkgconfig                 1.3.1                    py36_1    conda-forge
ptscotch                  6.0.5                ha5050ec_0    conda-forge
pybind11                  2.2.4            py36h2d50403_1    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
rhash                     1.3.4                         0    conda-forge
scalapack                 2.0.2                h186ce0b_3    conda-forge
scotch                    6.0.5                h9c0d707_1    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
slepc                     3.9.2           blas_openblashe63b0ae_0  [blas_openblas]  conda-forge
slepc4py                  3.9.0            py36h7eb728f_1    conda-forge
sqlite                    3.24.0               h2f33b56_1    conda-forge
suitesparse               4.5.6           blas_openblash55dcaef_201  [blas_openblas]  conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tbb                       2018_20171205                 0    conda-forge
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

     active environment : fenicsproject
    active env location : /root/miniconda3/envs/fenicsproject
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.17.0-1-amd64 ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False

2018.1.0
(fenicsproject) root@35e3103876f0:/# 
```

</details>

**Comment by jan-janssen** [comment] 2021-11-18 14:33
This should be fixed now, otherwise feel free to open a new issue.

**Closed by jan-janssen** 2021-11-18 14:33 UTC
