### ISSUE TITLE
Verification fails with python 3.9

### ISSUE THREAD

**Issue by abhi-k9** [conda-forge/fenics-feedstock#146] opened 2021-11-10 17:35 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
conda create --name my_env -c conda-forge python=3.9 fenics

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

    active environment : base
    active env location : /users/me/workspace/tools/miniconda
            shell level : 1
       user config file : /users/me/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.9.1.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /users/me/workspace/tools/miniconda  (writable)
      conda av data dir : /users/me/workspace/tools/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /users/me/workspace/tools/miniconda/pkgs
                          /users/me/.conda/pkgs
       envs directories : /users/me/workspace/tools/miniconda/envs
                          /users/me/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.1 Linux/3.10.0-1160.36.2.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 31824:4410
             netrc file : None
           offline mode : False

```
</details>

Trying to install _fenics_ with _python 3.9_ gives following error.

```
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/fenics_ufl-2019.1.0.dist-info/direct_url.json'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/fenics_ufl-2019.1.0.dist-info/top_level.txt'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/ufl/core/__init__.py'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/ufl/corealg/__init__.py'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/ufl/formatting/__init__.py'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/ufl/measureoperators.py'
specified in the package manifest cannot be found.
CondaVerificationError: The package for fenics-ufl located at /users/PAS1064/k09/workspace/tools/miniconda/pkgs/fenics-ufl-2019.1.0-py39hf3d152e_23
appears to be corrupted. The path 'lib/python3.9/site-packages/ufl/utils/__init__.py'
specified in the package manifest cannot be found.
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::suitesparse-5.10.1-h9e50725_1, conda-forge/linux-64::superlu_dist-7.1.1-h25dcc4a_0
  path: 'include/colamd.h'
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::superlu-5.2.2-h16cfea0_0, conda-forge/linux-64::superlu_dist-7.1.1-h25dcc4a_0
  path: 'include/superlu_enum_consts.h'
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::superlu-5.2.2-h16cfea0_0, conda-forge/linux-64::superlu_dist-7.1.1-h25dcc4a_0
  path: 'include/supermatrix.h'
```

It works if I constraint _python_ to version _3.7_

**Comment by jan-janssen** [comment] 2021-11-18 14:00
I released a new version, can you check if this fixes the issue?

**Comment by abhi-k9** [comment] 2021-11-18 15:43
Yes it fixed the issue. Thanks!

Was this caused due to both `superlu-5.2.2` and `superlu-7.1.1` being used at the same time for dependency resolution before?

**Comment by jan-janssen** [comment] 2021-11-18 16:26
yes, there was an issue with `superlu_dist` the issue is now fixed and I updated the `superlu_dist` recipe to prevent similar issues in the future. I hope the `fenics` conda package becomes more stable now.

**Closed by jan-janssen** 2021-11-18 16:26 UTC
