### ISSUE TITLE
link hdf5

### ISSUE THREAD

**Issue by minrk** [conda-forge/fenics-feedstock#5] opened 2016-10-24 15:15 UTC
fenics should link hdf5, but it should be a parallel build and conda-forge only has a serial hdf5 package.

cf https://github.com/conda-forge/hdf5-feedstock/issues/51

**Comment by garth-wells** [comment] 2016-10-29 11:22
We're working towards supporting serial HDF5 in DOLFIN.

**Comment by johannesring** [comment] 2017-06-14 16:08
Does DOLFIN 2017.1 work with serial HDF5? In that case, we should enable this and rebuild the package.

**Comment by garth-wells** [comment] 2017-06-14 16:19
@chrisrichardson says that DOLFIN 2017.1 works with serial HDF5.

**Comment by johannesring** [comment] 2017-06-14 16:21
Good - I will try to add it.

**Comment by johannesring** [comment] 2017-06-15 07:59
I can confirm that the serial HDF5 seems to be working fine with DOLFIN.

**Comment by johannesring** [comment] 2017-06-15 08:00
Fixed in pull request #45.

**Closed by johannesring** 2017-06-15 08:00 UTC
