### ISSUE TITLE
ModuleNotFoundError: No module named '_common'

### ISSUE THREAD

**Issue by lbluque** [conda-forge/fenics-feedstock#46] opened 2017-06-15 23:26 UTC
Maybe similar to #15 & #21
I am trying to install fenics from Anaconda on Linux:

`4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux`

I am using miniconda3, python=3.6.1, conda=4.3.21

I created an environment and installed with:

`conda create -n fenicsproject -c conda-forge fenics`

fenics=2017.1.0 is succesfully installed, but when running: `import fenics`

I get the following error:

```File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/lbluque/.conda/envs/fenicsproject/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: /home/lbluque/.conda/envs/fenicsproject/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /usr/local/lib/python3.6/site-packages/dolfin/cpp/_common.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/usr/local/lib/python3.6/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/home/lbluque/.conda/envs/fenicsproject/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)```

I have libgcc=5.2.0 installed in my environment.

**Comment by ChrisRackauckas** [comment] 2017-06-17 09:47
I'm having the same issue on CentOS 7. Recent fenics update did:

```
The following packages will be UPDATED:

    fenics:    2016.1.0-py27_1    conda-forge --> 2017.1.0-py27_2 conda-forge

The following packages will be DOWNGRADED:

    boost:     1.64.0-np113py27_2 conda-forge --> 1.63.0-py27_5   conda-forge
    boost-cpp: 1.64.0-1           conda-forge --> 1.63.0-2        conda-forge
```

and now:

```
ImportError('No module named _common',)
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
```

**Comment by Phesao** [comment] 2017-06-20 12:48
I have the same issue. Downgrading fenics to an older version works for me as a workaround.

**Comment by lbluque** [comment] 2017-06-20 18:20
Unfortunately downgrading is not doing it for me. I tried 2016.2.0 and 2016.1.0

```
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/lbluque/.conda/envs/fenicsproject/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /home/lbluque/.conda/envs/fenicsproject/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/lib/python3.6/site-packages/dolfin/cpp/_common.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/usr/local/lib/python3.6/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/home/lbluque/.conda/envs/fenicsproject/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_common'
```

**Comment by johannesring** [comment] 2017-06-21 07:54
There is a new updated package now that fixes a similar issue (see issue #47). They might be related, so please try updating the fenics package and see if that fixes the problem.

**Comment by ChrisRackauckas** [comment] 2017-07-04 13:48
Still occurs.

**Comment by isuruf** [comment] 2017-07-04 14:39
One issue I can see in the case of @ChrisRackauckas is that the system `libstdc++.so` is older than the `libstdc++.so` in the conda environment and julia loads the system lib on startup.

@ChrisRackauckas, can you try the following to start julia and and see if that works.

    `LD_PRELOAD=/home/crackauc/.julia/v0.5/Conda/deps/usr/lib/libstdc++.so.6 julia`

If it works, let's figure out what we can do.

**Comment by kilojoules** [comment] 2017-07-07 17:01
I have the same problem on mac

    $ conda create -n fenicstest -c conda-forge python=2.7 fenics=2016.1 dolfin-adjoint=2016.1 
    Fetching package metadata ...
    
    
    ........
    Solving package specifications: .
    
    Package plan for installation in environment /Users/jquick/miniconda3/envs/fenicstest:
    
    The following NEW packages will be INSTALLED:
    
        blas:            1.1-openblas                  conda-forge
        boost:           1.61.0-py27_2                 conda-forge
        bzip2:           1.0.6-1                       conda-forge
        ca-certificates: 2017.4.17-0                   conda-forge
        certifi:         2017.4.17-py27_0              conda-forge
        cmake:           3.8.0-2                       conda-forge
        curl:            7.52.1-0                      conda-forge
        dolfin-adjoint:  2016.1.0-py27_1               conda-forge
        eigen:           3.3.3-0                       conda-forge
        expat:           2.2.1-0                       conda-forge
        fastcache:       1.0.2-py27_0                  conda-forge
        fenics:          2016.1.0-py27_5               conda-forge
        icu:             56.1-4                        conda-forge
        libadjoint:      2016.1.0-py27_1               conda-forge
        libgfortran:     3.0.0-0                       conda-forge
        libuv:           1.11.0-0                      conda-forge
        metis:           5.1.0-3                       conda-forge
        mpich:           3.2-4                         conda-forge
        mpmath:          0.19-py27_2                   conda-forge
        ncurses:         5.9-10                        conda-forge
        numpy:           1.13.1-py27_blas_openblas_200 conda-forge [blas_openblas]
        openblas:        0.2.19-2                      conda-forge
        openssl:         1.0.2l-0                      conda-forge
        pcre:            8.39-0                        conda-forge
        petsc:           3.7.4-blas_openblas_5         conda-forge [blas_openblas]
        petsc4py:        3.7.0-py27_1                  conda-forge
        pip:             9.0.1-py27_0                  conda-forge
        pkg-config:      0.29.1-1                      conda-forge
        ply:             3.9-py27_0                    conda-forge
        ptscotch:        6.0.4-2                       conda-forge
        python:          2.7.13-1                      conda-forge
        readline:        6.2-0                         conda-forge
        rhash:           1.3.4-0                       conda-forge
        setuptools:      33.1.1-py27_0                 conda-forge
        six:             1.10.0-py27_1                 conda-forge
        slepc:           3.7.1-2                       conda-forge
        slepc4py:        3.7.0-py27_0                  conda-forge
        sqlite:          3.13.0-1                      conda-forge
        suitesparse:     4.5.4-blas_openblas_200       conda-forge [blas_openblas]
        swig:            3.0.11-0                      conda-forge
        sympy:           1.1-py27_0                    conda-forge
        tbb:             2017_20170604-1               conda-forge
        tk:              8.5.19-1                      conda-forge
        wheel:           0.29.0-py27_0                 conda-forge
        xz:              5.2.2-0                       conda-forge
        zlib:            1.2.11-0                      conda-forge
    
    Proceed ([y]/n)? 
    bzip2-1.0.6-1. 100% |######################################################################################| Time: 0:00:00 592.72 kB/s
    ca-certificate 100% |######################################################################################| Time: 0:00:00 938.91 kB/s
    eigen-3.3.3-0. 100% |######################################################################################| Time: 0:00:00   1.67 MB/s
    
    expat-2.2.1-0. 100% |######################################################################################| Time: 0:00:00  11.02 MB/s
    icu-56.1-4.tar 100% |######################################################################################| Time: 0:00:03   7.33 MB/s
    libgfortran-3. 100% |######################################################################################| Time: 0:00:00   6.27 MB/s
    libuv-1.11.0-0 100% |######################################################################################| Time: 0:00:00   4.89 MB/s
    metis-5.1.0-3. 100% |######################################################################################| Time: 0:00:00   2.09 MB/s
    ncurses-5.9-10 100% |######################################################################################| Time: 0:00:00   2.44 MB/s
    pcre-8.39-0.ta 100% |######################################################################################| Time: 0:00:00   2.55 MB/s
    rhash-1.3.4-0. 100% |######################################################################################| Time: 0:00:00   1.82 MB/s
    sqlite-3.13.0- 100% |######################################################################################| Time: 0:00:00   2.82 MB/s
    tbb-2017_20170 100% |######################################################################################| Time: 0:00:00   6.04 MB/s
    tk-8.5.19-1.ta 100% |######################################################################################| Time: 0:00:00   4.01 MB/s
    xz-5.2.2-0.tar 100% |######################################################################################| Time: 0:00:00   3.28 MB/s
    zlib-1.2.11-0. 100% |######################################################################################| Time: 0:00:00   2.17 MB/s
    mpich-3.2-4.ta 100% |######################################################################################| Time: 0:00:01   4.20 MB/s
    openblas-0.2.1 100% |######################################################################################| Time: 0:00:02   6.19 MB/s
    openssl-1.0.2l 100% |######################################################################################| Time: 0:00:00   4.73 MB/s
    pkg-config-0.2 100% |######################################################################################| Time: 0:00:00   1.97 MB/s
    readline-6.2-0 100% |######################################################################################| Time: 0:00:00   1.57 MB/s
    blas-1.1-openb 100% |######################################################################################| Time: 0:00:00   1.31 MB/s
    curl-7.52.1-0. 100% |######################################################################################| Time: 0:00:00   1.43 MB/s
    ptscotch-6.0.4 100% |######################################################################################| Time: 0:00:00   2.58 MB/s
    python-2.7.13- 100% |######################################################################################| Time: 0:00:01   5.13 MB/s
    boost-1.61.0-p 100% |######################################################################################| Time: 0:00:02   4.87 MB/s
    certifi-2017.4 100% |######################################################################################| Time: 0:00:00   5.03 MB/s
    cmake-3.8.0-2. 100% |######################################################################################| Time: 0:00:01   5.96 MB/s
    fastcache-1.0. 100% |######################################################################################| Time: 0:00:00  15.28 MB/s
    mpmath-0.19-py 100% |######################################################################################| Time: 0:00:00   1.82 MB/s
    numpy-1.13.1-p 100% |######################################################################################| Time: 0:00:01   2.58 MB/s
    ply-3.9-py27_0 100% |######################################################################################| Time: 0:00:00  13.98 MB/s
    six-1.10.0-py2 100% |######################################################################################| Time: 0:00:00 931.50 kB/s
    suitesparse-4. 100% |######################################################################################| Time: 0:00:01   2.29 MB/s
    petsc-3.7.4-bl 100% |######################################################################################| Time: 0:00:01   3.02 MB/s
    setuptools-33. 100% |######################################################################################| Time: 0:00:00   3.37 MB/s
    swig-3.0.11-0. 100% |######################################################################################| Time: 0:00:00   2.90 MB/s
    sympy-1.1-py27 100% |######################################################################################| Time: 0:00:02   3.30 MB/s
    petsc4py-3.7.0 100% |######################################################################################| Time: 0:00:00   3.05 MB/s
    slepc-3.7.1-2. 100% |######################################################################################| Time: 0:00:00   2.99 MB/s
    wheel-0.29.0-p 100% |######################################################################################| Time: 0:00:00   5.91 MB/s
    libadjoint-201 100% |######################################################################################| Time: 0:00:00   1.92 MB/s
    pip-9.0.1-py27 100% |######################################################################################| Time: 0:00:00   3.23 MB/s
    slepc4py-3.7.0 100% |######################################################################################| Time: 0:00:00   2.11 MB/s
    fenics-2016.1. 100% |######################################################################################| Time: 0:00:02   3.19 MB/s
    dolfin-adjoint 100% |######################################################################################| Time: 0:00:00   1.81 MB/s
    #
    # To activate this environment, use:
    # > source activate fenicstest
    #
    # To deactivate this environment, use:
    # > source deactivate fenicstest
    #
    
    ~/SE/AeroelasticSE/src/AeroelasticSE/FAST_mdao/wrapper_examples $ 
    ~/SE/AeroelasticSE/src/AeroelasticSE/FAST_mdao/wrapper_examples $ 
    ~/SE/AeroelasticSE/src/AeroelasticSE/FAST_mdao/wrapper_examples $ 
    ~/SE/AeroelasticSE/src/AeroelasticSE/FAST_mdao/wrapper_examples $ cd ~/activesubspaces/
    ~/activesubspaces $ source activate fenicstest
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ python 
    .git/                AIAA.ipynb           README.md            data/                pow.py               
    .pow.py.swp          AIAA2018/            WindSE2DImproved.py  mdao.py              xgboost.py           
    (fenicstest) ~/activesubspaces $ python WindSE2DImproved.py 
    
    
    
    Traceback (most recent call last):
      File "WindSE2DImproved.py", line 1, in <module>
        from dolfin import *
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>
        from . import cpp
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
        exec("from . import %s" % module_name)
      File "<string>", line 1, in <module>
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/common.py", line 25, in <module>
        _common = swig_import_helper()
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/common.py", line 24, in swig_import_helper
        return importlib.import_module('_common')
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named _common
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ conda search fenics --channel conda-forge
    Fetching package metadata ...........
    fenics                       2016.1.0                 py27_0  conda-forge     
                                 2016.1.0                 py35_0  conda-forge     
                                 2016.1.0                 py27_1  conda-forge     
                                 2016.1.0                 py34_1  conda-forge     
                                 2016.1.0                 py35_1  conda-forge     
                                 2016.1.0                 py27_2  conda-forge     
                                 2016.1.0                 py34_2  conda-forge     
                                 2016.1.0                 py35_2  conda-forge     
                                 2016.1.0                 py27_3  conda-forge     
                                 2016.1.0                 py34_3  conda-forge     
                                 2016.1.0                 py35_3  conda-forge     
                                 2016.1.0                 py27_4  conda-forge     
                                 2016.1.0                 py34_4  conda-forge     
                                 2016.1.0                 py35_4  conda-forge     
                              *  2016.1.0                 py27_5  conda-forge     
                                 2016.1.0                 py34_5  conda-forge     
                                 2016.1.0                 py35_5  conda-forge     
                                 2016.2.0                 py27_0  conda-forge     
                                 2016.2.0                 py34_0  conda-forge     
                                 2016.2.0                 py35_0  conda-forge     
                                 2016.2.0                 py27_2  conda-forge     
                                 2016.2.0                 py34_2  conda-forge     
                                 2016.2.0                 py35_2  conda-forge     
                                 2016.2.0                 py27_3  conda-forge     
                                 2016.2.0                 py34_3  conda-forge     
                                 2016.2.0                 py35_3  conda-forge     
                                 2016.2.0                 py27_4  conda-forge     
                                 2016.2.0                 py34_4  conda-forge     
                                 2016.2.0                 py35_4  conda-forge     
                                 2016.2.0                 py27_5  conda-forge     
                                 2016.2.0                 py35_5  conda-forge     
                                 2016.2.0                 py36_5  conda-forge     
                                 2016.2.0                 py27_6  conda-forge     
                                 2016.2.0                 py35_6  conda-forge     
                                 2016.2.0                 py36_6  conda-forge     
                                 2017.1.0                 py27_0  conda-forge     
                                 2017.1.0                 py35_0  conda-forge     
                                 2017.1.0                 py36_0  conda-forge     
                                 2017.1.0                 py27_1  conda-forge     
                                 2017.1.0                 py35_1  conda-forge     
                                 2017.1.0                 py36_1  conda-forge     
                                 2017.1.0                 py27_2  conda-forge     
                                 2017.1.0                 py35_2  conda-forge     
                                 2017.1.0                 py36_2  conda-forge     
                                 2017.1.0                 py27_3  conda-forge     
                                 2017.1.0                 py35_3  conda-forge     
                                 2017.1.0                 py36_3  conda-forge     
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ 
    (fenicstest) ~/activesubspaces $ conda install fenics
    Fetching package metadata .........
    Solving package specifications: .
    
    # All requested packages already installed.
    # packages in environment at /Users/jquick/miniconda3/envs/fenicstest:
    #
    fenics                    2016.1.0                 py27_5    conda-forge
    (fenicstest) ~/activesubspaces $ python WindSE2DImproved.py 
    Traceback (most recent call last):
      File "WindSE2DImproved.py", line 1, in <module>
        from dolfin import *
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>
        from . import cpp
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
        exec("from . import %s" % module_name)
      File "<string>", line 1, in <module>
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/common.py", line 25, in <module>
        _common = swig_import_helper()
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/site-packages/dolfin/cpp/common.py", line 24, in swig_import_helper
        return importlib.import_module('_common')
      File "/Users/jquick/miniconda3/envs/fenicstest/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named _common

**Closed** 2017-07-10 13:20 UTC

**Comment by shihu4937** [comment] 2017-08-14 20:52
I had exactly the same problem right now, did you guys found the solutions?

**Comment by isuruf** [comment] 2017-08-17 15:02
@shihu4937, can you try `conda install libgcc=4.8`?

**Comment by srody** [comment] 2017-08-17 23:47
@isuruf , I am also getting this error message, and libgcc=4.8 did not work for me.

**Comment by shihu4937** [comment] 2017-08-18 00:19
@isuruf Thank you for your reply.   I think my problem is caused by "messing different environment of Fenics. the spyder is launched in root envs, however I changed the envs to fenicsproject in anaconda manully.  another thing is making sure to set the python interpreter correctly in spyder setting.  Now it worked without problem.
